####################################################################################################
######################################## DATABASE CONNECTION #######################################
####################################################################################################

MYSQL_HOST: ""
MYSQL_USER: ""
MYSQL_PASSWORD: ""
MYSQL_DATABASE: ""

####################################################################################################
######################################## CUSTOM VARIABLES #########################################
####################################################################################################

JWT_SECRET_KEY: ""
SERVICE_VERSION: "v1"
