####################################################################################################
######################################## DATABASE CONNECTION #######################################
####################################################################################################

MYSQL_HOST: "127.0.0.1"
MYSQL_USER: "root"
MYSQL_PASSWORD: "123456"
MYSQL_DATABASE: "service-tickets"

####################################################################################################
######################################## CUSTOM VARIABLES #########################################
####################################################################################################

JWT_SECRET_KEY: "6!9#fLWpCB#vR8+9rnTD#4!TGvMTGRVM"
SERVICE_VERSION: "v1"
