####################################################################################################
######################################## DATABASE CONNECTION #######################################
####################################################################################################

MYSQL_HOST: ""
MYSQL_USER: ""
MYSQL_PASSWORD: ""
MYSQL_DATABASE: ""

####################################################################################################
######################################## CUSTOM VARIABLES #########################################
####################################################################################################

SERVICE_VERSION: "v1"
