service: service-payments

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  environment:
    MYSQL_HOST: ${file(config/stage.${self:provider.stage}.yml):MYSQL_HOST}
    MYSQL_USER: ${file(config/stage.${self:provider.stage}.yml):MYSQL_USER}
    MYSQL_PASSWORD: ${file(config/stage.${self:provider.stage}.yml):MYSQL_PASSWORD}
    MYSQL_DATABASE: ${file(config/stage.${self:provider.stage}.yml):MYSQL_DATABASE}
    JWT_SECRET_KEY: ${file(config/stage.${self:provider.stage}.yml):JWT_SECRET_KEY}

plugins:
  - serverless-offline

custom:
  SERVICE_VERSION: ${file(config/stage.${self:provider.stage}.yml):SERVICE_VERSION}

### Routes.

functions:
  # Make payment
  post_payment:
    handler: src/lambda/post.handler
    events:
    - http:
        method: post
        path: /tickets/${self:custom.SERVICE_VERSION}
