service: service-tickets

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  environment:
    MYSQL_HOST: ${file(config/stage.${self:provider.stage}.yml):MYSQL_HOST}
    MYSQL_USER: ${file(config/stage.${self:provider.stage}.yml):MYSQL_USER}
    MYSQL_PASSWORD: ${file(config/stage.${self:provider.stage}.yml):MYSQL_PASSWORD}
    MYSQL_DATABASE: ${file(config/stage.${self:provider.stage}.yml):MYSQL_DATABASE}

plugins:
  - serverless-offline

custom:
  SERVICE_VERSION: ${file(config/stage.${self:provider.stage}.yml):SERVICE_VERSION}

### Routes.

functions:
  # Get ticket info
  get_ticket:
    handler: src/lambda/get.handler
    events:
    - http:
        method: get
        path: /tickets/${self:custom.SERVICE_VERSION}/{id}
  # Create ticket
  post_ticket:
    handler: src/lambda/post.handler
    events:
    - http:
        method: post
        path: /tickets/${self:custom.SERVICE_VERSION}
